version: '3.4'

services:
  spystore.service:
    image: ${DOCKER_REGISTRY}spystoreservice
    container_name: spyservice
    build:
      context: .
      dockerfile: ..\SpyStore.Service\SpyStore.Service\Dockerfile

  spystore.mvc:
    image: ${DOCKER_REGISTRY}spystoremvc
    container_name: spymvc
    build:
      context: .
      dockerfile: SpyStore.MVC\Dockerfile
    depends_on:
      - spystore.service
    ports:
      - "5000:80"