version: '3.4'

services:
  spystore.mvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  spystore.service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

networks:
  default:
    external:
      name: nat

